DROP TABLE IF EXISTS ITEMS CASCADE;

CREATE TABLE ITEMS
(
		id INT PRIMARY KEY,
        ITEM_NO VARCHAR(50), 
        KIND VARCHAR(50), 
        NAME VARCHAR(300), 
        PRICE INT,  
        STOCK INT
);